name: Build

on: [ push, pull_request ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Run Data Generation
      run: ./gradlew fabric:runDatagen
      env:
        CI: 'true'
    - name: Build artifacts
      run: ./gradlew build
    - name: Get build hash
      id: get-build-hash
      run: |
        echo "id=$(echo ${{github.sha}} | cut -c 1-7)" >> $GITHUB_OUTPUT
    - name: Get branch name
      id: get-branch
      shell: bash
      run: |
        echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4.3.3
      with:
        name: moderner-beta-${{steps.get-branch.outputs.branch}}-${{steps.get-build-hash.outputs.id}}
        path: |
          neoforge/build/libs
          fabric/build/libs
