name: Mod Publish

on:
  push:
    tags: ["**"]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Run Data Generation
        run: ./gradlew fabric:runDatagen
        env:
          CI: 'true'
      - name: Build and publish
        run: ./gradlew build modrinth --stacktrace
        env:
          MODRINTH_TOKEN: ${{secrets.MODRINTH_TOKEN}}
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4.3.3
        with:
          name: moderner-beta-${{github.ref_name}}
          path: |
            neoforge/build/libs
            fabric/build/libs
      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          body_path: CHANGELOG.md
          files: |
            neoforge/build/libs/*-neoforge.jar
            fabric/build/libs/*-fabric.jar
